### ISSUE TITLE
Add rootSift to demoSIft

### ISSUE THREAD

**Issue by simogasp** [thierrymalon/DBoW2#2]
Add a flag to pass at command line to use the rootSift instead the classical SIFT. RootSIFT is just like SIFT, but we normalize the extracted descriptors: 

``` cpp
extractor->compute( img, kpts, descriptors );
if( root )
{
    for(int i = 0; i < descriptors.rows; ++i )
    {
        sqrt( descriptors.row(i) /  sum(descriptors.row(i)).val[0] , descriptors.row(i) );
    }
}
```
- [x] add the option to the command line (eg `-r`)
- [x] add the flag to the `loadFeatures` function
- [x] add the code 
- [x] change return type of the `loadFeatures` function from void to bool, and return true if the .desc files already exist but are not adapted to the line command (.desc containing rootSift descriptors but sift descriptors asked, or .desc containing sift descriptors but rootSift descriptors asked). This bool value will be used in vocCreation parameters to know if the vocabulary file .yml.gz is correct or should be recomputed from zero.
- [x] add a flag `isOK` to the `vocCreation` function, specifying if the vocabulary file is OK (adapted to the asked descriptors type)
- [x] add the code for vocCreation: if isOK is false, the vocabulary need to be recomputed

**Comment by thierrymalon** [comment]
Forgot to close it.
